version: '3.1'
services:
  db:
    image: postgres
    container_name: caixaeletronico
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sg
      POSTGRES_DB: caixaeletronico
    ports:
      - "3309:5432"
    volumes:
      - caixaeletronico:/var/lib/postgres

volumes:
  caixaeletronico: